name: Publish dotnet code

on:
  push:
    branches: [ main ]

jobs:
  dotnet_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet 
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.105
    - name: Publish
      run: dotnet publish --output ./publish
    - name: list published
      run: ls ./publish